### ISSUE TITLE
Is it possible to use timestamp in MySQL

### ISSUE THREAD

**Issue by thelonious** [notheotherben/node-orm-timestamps#6]
I'm pretty sure I know the answer to this already, but I have to ask :) Is there any way to use "timestamp" as the column type for MySQL? I prefer using that type because it is timezone independent. I've hacked orm to allow this type for MySQL, but I'd much rather use this nice plugin instead.

Thanks!
Kevin

**Comment by notheotherben** [comment]
It is possible, simply change the `dbtype` property to whatever you wish. The only issue I can foresee is that _orm_ doesn't know about the `timestamp` field type. That being said, if you're using a version of _orm_ which is capable of handling the `timestamp` column type then doing the following will work:

``` js
var modts = require('orm-timestamps');

db.use(modts, {
        dbtype: { type: 'timestamp' },
        now: function() { return new Date(); }
    });
```

If necessary, change the `now` function to return a type compatible with your `timestamp` implementation.

**Comment by thelonious** [comment]
Unfortunately, ORM doesn't allow me to use that type—Error: Unknown property type: timestamp—at least, not without some code changes. However, that's an ORM issue an not an issue with this plugin.
